use super::inst_enum::{AddressMode, Instruction};
use crate::cpu::Cpu;
use crate::cpu::Flags;
mod arithmetic;
mod branches;
mod incdec;
mod jumpcall;
mod loadstore;
mod logical;
mod registertransfer;
mod shifts;
mod stackoperations;
mod systemfunctions;
mod unofficial;

impl Cpu {
    pub fn push(&mut self, byte: u8) {
        let address = 0x100 + (self.sp as u16);
        self.sp = self.sp.wrapping_sub(1);
        self.cpu_write(address, byte);
    }
    pub fn pop(&mut self) -> u8 {
        self.sp = self.sp.wrapping_add(1);
        let address = 0x100 + (self.sp as u16);
        self.cpu_read(address, false)
    }
    pub fn handle_opcode(&mut self, opcode: u8) {
        match opcode {
            0xA9 => self.handle_operation(AddressMode::Immediate, Instruction::LDA, 2),
            0xA5 => self.handle_operation(AddressMode::ZeroPage, Instruction::LDA, 3),
            0xB5 => self.handle_operation(AddressMode::ZeroPageX, Instruction::LDA, 4),
            0xAD => self.handle_operation(AddressMode::Absolute, Instruction::LDA, 4),
            0xBD => self.handle_operation(AddressMode::AbsoluteX, Instruction::LDA, 4),
            0xB9 => self.handle_operation(AddressMode::AbsoluteY, Instruction::LDA, 4),
            0xA1 => self.handle_operation(AddressMode::IDX, Instruction::LDA, 6),
            0xB1 => self.handle_operation(AddressMode::IDY, Instruction::LDA, 5),
            0xA2 => self.handle_operation(AddressMode::Immediate, Instruction::LDX, 2),
            0xA6 => self.handle_operation(AddressMode::ZeroPage, Instruction::LDX, 3),
            0xB6 => self.handle_operation(AddressMode::ZeroPageY, Instruction::LDX, 4),
            0xAE => self.handle_operation(AddressMode::Absolute, Instruction::LDX, 4),
            0xBE => self.handle_operation(AddressMode::AbsoluteY, Instruction::LDX, 4),
            0xA0 => self.handle_operation(AddressMode::Immediate, Instruction::LDY, 2),
            0xA4 => self.handle_operation(AddressMode::ZeroPage, Instruction::LDY, 3),
            0xB4 => self.handle_operation(AddressMode::ZeroPageX, Instruction::LDY, 4),
            0xAC => self.handle_operation(AddressMode::Absolute, Instruction::LDY, 4),
            0xBC => self.handle_operation(AddressMode::AbsoluteX, Instruction::LDY, 4),
            0x85 => self.handle_operation(AddressMode::ZeroPage, Instruction::STA, 3),
            0x95 => self.handle_operation(AddressMode::ZeroPageX, Instruction::STA, 4),
            0x8D => self.handle_operation(AddressMode::Absolute, Instruction::STA, 4),
            0x9D => self.handle_operation(AddressMode::AbsoluteX, Instruction::STA, 5),
            0x99 => self.handle_operation(AddressMode::AbsoluteY, Instruction::STA, 5),
            0x81 => self.handle_operation(AddressMode::IDX, Instruction::STA, 6),
            0x91 => self.handle_operation(AddressMode::IDY, Instruction::STA, 6),
            0x86 => self.handle_operation(AddressMode::ZeroPage, Instruction::STX, 3),
            0x96 => self.handle_operation(AddressMode::ZeroPageY, Instruction::STX, 4),
            0x8E => self.handle_operation(AddressMode::Absolute, Instruction::STX, 4),
            0x84 => self.handle_operation(AddressMode::ZeroPage, Instruction::STY, 3),
            0x94 => self.handle_operation(AddressMode::ZeroPageX, Instruction::STY, 4),
            0x8C => self.handle_operation(AddressMode::Absolute, Instruction::STY, 4),
            0xAA => self.handle_operation(AddressMode::Implicit, Instruction::TAX, 2),
            0xA8 => self.handle_operation(AddressMode::Implicit, Instruction::TAY, 2),
            0x8A => self.handle_operation(AddressMode::Implicit, Instruction::TXA, 2),
            0x98 => self.handle_operation(AddressMode::Implicit, Instruction::TYA, 2),
            0xBA => self.handle_operation(AddressMode::Implicit, Instruction::TSX, 2),
            0x9A => self.handle_operation(AddressMode::Implicit, Instruction::TXS, 2),
            0x48 => self.handle_operation(AddressMode::Implicit, Instruction::PHA, 3),
            0x08 => self.handle_operation(AddressMode::Implicit, Instruction::PHP, 3),
            0x68 => self.handle_operation(AddressMode::Implicit, Instruction::PLA, 4),
            0x28 => self.handle_operation(AddressMode::Implicit, Instruction::PLP, 4),
            0x29 => self.handle_operation(AddressMode::Immediate, Instruction::AND, 2),
            0x25 => self.handle_operation(AddressMode::ZeroPage, Instruction::AND, 3),
            0x35 => self.handle_operation(AddressMode::ZeroPageX, Instruction::AND, 4),
            0x2D => self.handle_operation(AddressMode::Absolute, Instruction::AND, 4),
            0x3D => self.handle_operation(AddressMode::AbsoluteX, Instruction::AND, 4),
            0x39 => self.handle_operation(AddressMode::AbsoluteY, Instruction::AND, 4),
            0x21 => self.handle_operation(AddressMode::IDX, Instruction::AND, 6),
            0x31 => self.handle_operation(AddressMode::IDY, Instruction::AND, 5),
            0x49 => self.handle_operation(AddressMode::Immediate, Instruction::EOR, 2),
            0x45 => self.handle_operation(AddressMode::ZeroPage, Instruction::EOR, 3),
            0x55 => self.handle_operation(AddressMode::ZeroPageX, Instruction::EOR, 4),
            0x4D => self.handle_operation(AddressMode::Absolute, Instruction::EOR, 4),
            0x5D => self.handle_operation(AddressMode::AbsoluteX, Instruction::EOR, 4),
            0x59 => self.handle_operation(AddressMode::AbsoluteY, Instruction::EOR, 4),
            0x41 => self.handle_operation(AddressMode::IDX, Instruction::EOR, 6),
            0x51 => self.handle_operation(AddressMode::IDY, Instruction::EOR, 5),
            0x09 => self.handle_operation(AddressMode::Immediate, Instruction::ORA, 2),
            0x05 => self.handle_operation(AddressMode::ZeroPage, Instruction::ORA, 3),
            0x15 => self.handle_operation(AddressMode::ZeroPageX, Instruction::ORA, 4),
            0x0D => self.handle_operation(AddressMode::Absolute, Instruction::ORA, 4),
            0x1D => self.handle_operation(AddressMode::AbsoluteX, Instruction::ORA, 4),
            0x19 => self.handle_operation(AddressMode::AbsoluteY, Instruction::ORA, 4),
            0x01 => self.handle_operation(AddressMode::IDX, Instruction::ORA, 6),
            0x11 => self.handle_operation(AddressMode::IDY, Instruction::ORA, 5),
            0x24 => self.handle_operation(AddressMode::ZeroPage, Instruction::BIT, 3),
            0x2C => self.handle_operation(AddressMode::Absolute, Instruction::BIT, 4),
            0x69 => self.handle_operation(AddressMode::Immediate, Instruction::ADC, 2),
            0x65 => self.handle_operation(AddressMode::ZeroPage, Instruction::ADC, 3),
            0x75 => self.handle_operation(AddressMode::ZeroPageX, Instruction::ADC, 4),
            0x6D => self.handle_operation(AddressMode::Absolute, Instruction::ADC, 4),
            0x7D => self.handle_operation(AddressMode::AbsoluteX, Instruction::ADC, 4),
            0x79 => self.handle_operation(AddressMode::AbsoluteY, Instruction::ADC, 4),
            0x61 => self.handle_operation(AddressMode::IDX, Instruction::ADC, 6),
            0x71 => self.handle_operation(AddressMode::IDY, Instruction::ADC, 5),
            0xE9 => self.handle_operation(AddressMode::Immediate, Instruction::SBC, 2),
            0xE5 => self.handle_operation(AddressMode::ZeroPage, Instruction::SBC, 3),
            0xF5 => self.handle_operation(AddressMode::ZeroPageX, Instruction::SBC, 4),
            0xED => self.handle_operation(AddressMode::Absolute, Instruction::SBC, 4),
            0xFD => self.handle_operation(AddressMode::AbsoluteX, Instruction::SBC, 4),
            0xF9 => self.handle_operation(AddressMode::AbsoluteY, Instruction::SBC, 4),
            0xE1 => self.handle_operation(AddressMode::IDX, Instruction::SBC, 6),
            0xF1 => self.handle_operation(AddressMode::IDY, Instruction::SBC, 5),
            0xC9 => self.handle_operation(AddressMode::Immediate, Instruction::CMP, 2),
            0xC5 => self.handle_operation(AddressMode::ZeroPage, Instruction::CMP, 3),
            0xD5 => self.handle_operation(AddressMode::ZeroPageX, Instruction::CMP, 4),
            0xCD => self.handle_operation(AddressMode::Absolute, Instruction::CMP, 4),
            0xDD => self.handle_operation(AddressMode::AbsoluteX, Instruction::CMP, 4),
            0xD9 => self.handle_operation(AddressMode::AbsoluteY, Instruction::CMP, 4),
            0xC1 => self.handle_operation(AddressMode::IDX, Instruction::CMP, 6),
            0xD1 => self.handle_operation(AddressMode::IDY, Instruction::CMP, 5),
            0xE0 => self.handle_operation(AddressMode::Immediate, Instruction::CPX, 2),
            0xE4 => self.handle_operation(AddressMode::ZeroPage, Instruction::CPX, 3),
            0xEC => self.handle_operation(AddressMode::Absolute, Instruction::CPX, 4),
            0xC0 => self.handle_operation(AddressMode::Immediate, Instruction::CPY, 2),
            0xC4 => self.handle_operation(AddressMode::ZeroPage, Instruction::CPY, 3),
            0xCC => self.handle_operation(AddressMode::Absolute, Instruction::CPY, 4),
            0xE6 => self.handle_operation(AddressMode::ZeroPage, Instruction::INC, 5),
            0xF6 => self.handle_operation(AddressMode::ZeroPageX, Instruction::INC, 6),
            0xEE => self.handle_operation(AddressMode::Absolute, Instruction::INC, 6),
            0xFE => self.handle_operation(AddressMode::AbsoluteX, Instruction::INC, 7),
            0xE8 => self.handle_operation(AddressMode::Implicit, Instruction::INX, 2),
            0xC8 => self.handle_operation(AddressMode::Implicit, Instruction::INY, 2),
            0xC6 => self.handle_operation(AddressMode::ZeroPage, Instruction::DEC, 5),
            0xD6 => self.handle_operation(AddressMode::ZeroPageX, Instruction::DEC, 6),
            0xCE => self.handle_operation(AddressMode::Absolute, Instruction::DEC, 6),
            0xDE => self.handle_operation(AddressMode::AbsoluteX, Instruction::DEC, 7),
            0xCA => self.handle_operation(AddressMode::Implicit, Instruction::DEX, 2),
            0x88 => self.handle_operation(AddressMode::Implicit, Instruction::DEY, 2),
            0x0A => self.handle_operation(AddressMode::Accumulator, Instruction::ASL, 2),
            0x06 => self.handle_operation(AddressMode::ZeroPage, Instruction::ASL, 5),
            0x16 => self.handle_operation(AddressMode::ZeroPageX, Instruction::ASL, 6),
            0x0E => self.handle_operation(AddressMode::Absolute, Instruction::ASL, 6),
            0x1E => self.handle_operation(AddressMode::AbsoluteX, Instruction::ASL, 7),
            0x4A => self.handle_operation(AddressMode::Accumulator, Instruction::LSR, 2),
            0x46 => self.handle_operation(AddressMode::ZeroPage, Instruction::LSR, 5),
            0x56 => self.handle_operation(AddressMode::ZeroPageX, Instruction::LSR, 6),
            0x4E => self.handle_operation(AddressMode::Absolute, Instruction::LSR, 6),
            0x5E => self.handle_operation(AddressMode::AbsoluteX, Instruction::LSR, 7),
            0x2A => self.handle_operation(AddressMode::Accumulator, Instruction::ROL, 2),
            0x26 => self.handle_operation(AddressMode::ZeroPage, Instruction::ROL, 5),
            0x36 => self.handle_operation(AddressMode::ZeroPageX, Instruction::ROL, 6),
            0x2E => self.handle_operation(AddressMode::Absolute, Instruction::ROL, 6),
            0x3E => self.handle_operation(AddressMode::AbsoluteX, Instruction::ROL, 7),
            0x6A => self.handle_operation(AddressMode::Accumulator, Instruction::ROR, 2),
            0x66 => self.handle_operation(AddressMode::ZeroPage, Instruction::ROR, 5),
            0x76 => self.handle_operation(AddressMode::ZeroPageX, Instruction::ROR, 6),
            0x6E => self.handle_operation(AddressMode::Absolute, Instruction::ROR, 6),
            0x7E => self.handle_operation(AddressMode::AbsoluteX, Instruction::ROR, 7),
            0x4C => self.handle_operation(AddressMode::Absolute, Instruction::JMP, 3),
            0x6C => self.handle_operation(AddressMode::Indirect, Instruction::JMP, 5),
            0x20 => self.handle_operation(AddressMode::Absolute, Instruction::JSR, 6),
            0x60 => self.handle_operation(AddressMode::Implicit, Instruction::RTS, 6),
            0x90 => self.handle_operation(AddressMode::Relative, Instruction::BCC, 2),
            0xB0 => self.handle_operation(AddressMode::Relative, Instruction::BCS, 2),
            0xF0 => self.handle_operation(AddressMode::Relative, Instruction::BEQ, 2),
            0x30 => self.handle_operation(AddressMode::Relative, Instruction::BMI, 2),
            0xD0 => self.handle_operation(AddressMode::Relative, Instruction::BNE, 2),
            0x10 => self.handle_operation(AddressMode::Relative, Instruction::BPL, 2),
            0x50 => self.handle_operation(AddressMode::Relative, Instruction::BVC, 2),
            0x70 => self.handle_operation(AddressMode::Relative, Instruction::BVS, 2),
            0x18 => self.handle_operation(AddressMode::Implicit, Instruction::CLC, 2),
            0xD8 => self.handle_operation(AddressMode::Implicit, Instruction::CLD, 2),
            0x58 => self.handle_operation(AddressMode::Implicit, Instruction::CLI, 2),
            0xB8 => self.handle_operation(AddressMode::Implicit, Instruction::CLV, 2),
            0x38 => self.handle_operation(AddressMode::Implicit, Instruction::SEC, 2),
            0xF8 => self.handle_operation(AddressMode::Implicit, Instruction::SED, 2),
            0x78 => self.handle_operation(AddressMode::Implicit, Instruction::SEI, 2),
            0x00 => self.handle_operation(AddressMode::Implicit, Instruction::BRK, 7),
            0xEA => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0x40 => self.handle_operation(AddressMode::Implicit, Instruction::RTI, 6),
            /* Illegal opcodes */
            0x4 => self.handle_operation(AddressMode::ZeroPage, Instruction::NOP, 3),
            0x44 => self.handle_operation(AddressMode::ZeroPage, Instruction::NOP, 3),
            0x64 => self.handle_operation(AddressMode::ZeroPage, Instruction::NOP, 3),
            0xC => self.handle_operation(AddressMode::Absolute, Instruction::NOP, 4),
            0x14 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0x34 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0x54 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0x74 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0xD4 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0xf4 => self.handle_operation(AddressMode::ZeroPageX, Instruction::NOP, 4),
            0x1A => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0x3A => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0x5A => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0x7A => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0xDA => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0xFA => self.handle_operation(AddressMode::Implicit, Instruction::NOP, 2),
            0x80 => self.handle_operation(AddressMode::Immediate, Instruction::NOP, 2),
            0x82 | 0x89 => self.handle_operation(AddressMode::Immediate, Instruction::NOP, 2),
            0x1C => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0x3C => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0x5C => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0x7C => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0xDC => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0xFC => self.handle_operation(AddressMode::AbsoluteX, Instruction::NOP, 4),
            0xE2 => self.handle_operation(AddressMode::Immediate, Instruction::NOP, 2),
            0xC2 => self.handle_operation(AddressMode::Immediate, Instruction::NOP, 2),
            0x47 => self.handle_operation(AddressMode::ZeroPage, Instruction::SRE, 5),
            0x57 => self.handle_operation(AddressMode::ZeroPageX, Instruction::SRE, 6),
            0x4F => self.handle_operation(AddressMode::Absolute, Instruction::SRE, 6),
            0x5F => self.handle_operation(AddressMode::AbsoluteX, Instruction::SRE, 7),
            0x5B => self.handle_operation(AddressMode::AbsoluteY, Instruction::SRE, 7),
            0x43 => self.handle_operation(AddressMode::IDX, Instruction::SRE, 8),
            0x53 => self.handle_operation(AddressMode::IDY, Instruction::SRE, 8),
            0xA7 => self.handle_operation(AddressMode::ZeroPage, Instruction::LAX, 3),
            0xB7 => self.handle_operation(AddressMode::ZeroPageY, Instruction::LAX, 4),
            0xAF => self.handle_operation(AddressMode::Absolute, Instruction::LAX, 4),
            0xBF => self.handle_operation(AddressMode::AbsoluteY, Instruction::LAX, 4),
            0xA3 => self.handle_operation(AddressMode::IDX, Instruction::LAX, 6),
            0xB3 => self.handle_operation(AddressMode::IDY, Instruction::LAX, 5),
            0xBB => self.handle_operation(AddressMode::AbsoluteY, Instruction::LAS, 4),
            0x9C => self.handle_operation(AddressMode::AbsoluteX, Instruction::SHY, 5),
            0x67 => self.handle_operation(AddressMode::ZeroPage, Instruction::RRA, 5),
            0x77 => self.handle_operation(AddressMode::ZeroPageX, Instruction::RRA, 6),
            0x6F => self.handle_operation(AddressMode::Absolute, Instruction::RRA, 6),
            0x7F => self.handle_operation(AddressMode::AbsoluteX, Instruction::RRA, 7),
            0x7B => self.handle_operation(AddressMode::AbsoluteY, Instruction::RRA, 7),
            0x63 => self.handle_operation(AddressMode::IDX, Instruction::RRA, 8),
            0x73 => self.handle_operation(AddressMode::IDY, Instruction::RRA, 8),
            0xC7 => self.handle_operation(AddressMode::ZeroPage, Instruction::DCP, 5),
            0xD7 => self.handle_operation(AddressMode::ZeroPageX, Instruction::DCP, 6),
            0xCF => self.handle_operation(AddressMode::Absolute, Instruction::DCP, 6),
            0xDF => self.handle_operation(AddressMode::AbsoluteX, Instruction::DCP, 7),
            0xDB => self.handle_operation(AddressMode::AbsoluteY, Instruction::DCP, 7),
            0xC3 => self.handle_operation(AddressMode::IDX, Instruction::DCP, 8),
            0xD3 => self.handle_operation(AddressMode::IDY, Instruction::DCP, 8),
            0x87 => self.handle_operation(AddressMode::ZeroPage, Instruction::SAX, 3),
            0x97 => self.handle_operation(AddressMode::ZeroPageY, Instruction::SAX, 4),
            0x8F => self.handle_operation(AddressMode::Absolute, Instruction::SAX, 4),
            0x83 => self.handle_operation(AddressMode::IDX, Instruction::SAX, 6),
            0x27 => self.handle_operation(AddressMode::ZeroPage, Instruction::RLA, 5),
            0x37 => self.handle_operation(AddressMode::ZeroPageX, Instruction::RLA, 6),
            0x2F => self.handle_operation(AddressMode::Absolute, Instruction::RLA, 6),
            0x3F => self.handle_operation(AddressMode::AbsoluteX, Instruction::RLA, 7),
            0x3B => self.handle_operation(AddressMode::AbsoluteY, Instruction::RLA, 7),
            0x23 => self.handle_operation(AddressMode::IDX, Instruction::RLA, 8),
            0x33 => self.handle_operation(AddressMode::IDY, Instruction::RLA, 8),
            0x07 => self.handle_operation(AddressMode::ZeroPage, Instruction::SLO, 5),
            0x17 => self.handle_operation(AddressMode::ZeroPageX, Instruction::SLO, 6),
            0x0F => self.handle_operation(AddressMode::Absolute, Instruction::SLO, 6),
            0x1F => self.handle_operation(AddressMode::AbsoluteX, Instruction::SLO, 7),
            0x1B => self.handle_operation(AddressMode::AbsoluteY, Instruction::SLO, 7),
            0x03 => self.handle_operation(AddressMode::IDX, Instruction::SLO, 8),
            0x13 => self.handle_operation(AddressMode::IDY, Instruction::SLO, 8),
            0xE7 => self.handle_operation(AddressMode::ZeroPage,Instruction::ISC, 5),
            0xF7 => self.handle_operation(AddressMode::ZeroPageX,Instruction::ISC, 6),
            0xEF => self.handle_operation(AddressMode::Absolute,Instruction::ISC, 6),
            0xFF => self.handle_operation(AddressMode::AbsoluteX,Instruction::ISC, 7),
            0xFB => self.handle_operation(AddressMode::AbsoluteY,Instruction::ISC, 7),
            0xE3 => self.handle_operation(AddressMode::IDX,Instruction::ISC, 8),
            0xF3 => self.handle_operation(AddressMode::IDY,Instruction::ISC, 8),
            0x9B => self.handle_operation(AddressMode::AbsoluteY,Instruction::TAS, 5),
            0xAB => self.handle_operation(AddressMode::Immediate, Instruction::LXA, 2),
            0x02 | 0x12 | 0x22 | 0x32 | 0x42 | 0x52 | 0x62 | 0x72 | 0x92 | 0xB2 | 0xD2 | 0xF2 => self.handle_operation(AddressMode::Implicit, Instruction::JAM, 1),
            0x9E => self.handle_operation(AddressMode::AbsoluteY, Instruction::SHX, 5),
            0xCB => self.handle_operation(AddressMode::Immediate, Instruction::SBX, 2),
            0x8B => self.handle_operation(AddressMode::Immediate,Instruction::ANE, 2),
            0x9F => self.handle_operation(AddressMode::AbsoluteY, Instruction::SHA, 5),
            0x93 => self.handle_operation(AddressMode::IDY, Instruction::SHA, 6),
            0xEB => self.handle_operation(AddressMode::Immediate, Instruction::SBC, 2),
            0x6B => self.handle_operation(AddressMode::Immediate, Instruction::ARR, 2),
            0x4B => self.handle_operation(AddressMode::Immediate,Instruction::ALR,2),
            0xB | 0x2B => self.handle_operation(AddressMode::Immediate, Instruction::ANC, 2),
        };
    }

    pub fn handle_operation(
        &mut self,
        addrmode: AddressMode,
        instruction: Instruction,
        cycles: u8,
    ) {
        // println!("{:?}({:?})",instruction,addrmode);
        self.handle_addrmode(&addrmode);
        self.handle_instruction(instruction);
        self.cycles_left = self.cycles_left.wrapping_add(cycles as u16);
    }
    pub fn handle_addrmode(&mut self, addrmode: &AddressMode) {
        match addrmode {
            AddressMode::Implicit => self.implicit(),
            AddressMode::Accumulator => self.accumulator(),
            AddressMode::ZeroPage => self.zeropage(),
            AddressMode::ZeroPageX => self.zeropagex(),
            AddressMode::ZeroPageY => self.zeropagey(),
            AddressMode::Relative => self.relative(),
            AddressMode::Absolute => self.absolute(),
            AddressMode::AbsoluteX => self.absolutex(),
            AddressMode::AbsoluteY => self.absolutey(),
            AddressMode::Indirect => self.indirect(),
            AddressMode::IDX => self.idx(),
            AddressMode::IDY => self.idy(),
            AddressMode::Immediate => self.immediate(),
        };
    }
    fn handle_instruction(&mut self, instruction: Instruction) {
        match instruction {
            Instruction::LDA => self.lda(),
            Instruction::LDX => self.ldx(),
            Instruction::LDY => self.ldy(),
            Instruction::STA => self.sta(),
            Instruction::STX => self.stx(),
            Instruction::STY => self.sty(),
            Instruction::TAX => self.tax(),
            Instruction::TAY => self.tay(),
            Instruction::TXA => self.txa(),
            Instruction::TYA => self.tya(),
            Instruction::TSX => self.tsx(),
            Instruction::TXS => self.txs(),
            Instruction::PHA => self.pha(),
            Instruction::PHP => self.php(),
            Instruction::PLA => self.pla(),
            Instruction::PLP => self.plp(),
            Instruction::AND => self.and(),
            Instruction::EOR => self.eor(),
            Instruction::ORA => self.ora(),
            Instruction::BIT => self.bit(),
            Instruction::ADC => self.adc(),
            Instruction::SBC => self.sbc(),
            Instruction::CMP => self.cmp(),
            Instruction::CPX => self.cpx(),
            Instruction::CPY => self.cpy(),
            Instruction::INC => self.inc(),
            Instruction::INX => self.inx(),
            Instruction::INY => self.iny(),
            Instruction::DEC => self.dec(),
            Instruction::DEX => self.dex(),
            Instruction::DEY => self.dey(),
            Instruction::ASL => self.asl(),
            Instruction::LSR => self.lsr(),
            Instruction::ROL => self.rol(),
            Instruction::ROR => self.ror(),
            Instruction::JMP => self.jmp(),
            Instruction::JSR => self.jsr(),
            Instruction::RTS => self.rts(),
            Instruction::BCC => self.bcc(),
            Instruction::BCS => self.bcs(),
            Instruction::BEQ => self.beq(),
            Instruction::BMI => self.bmi(),
            Instruction::BNE => self.bne(),
            Instruction::BPL => self.bpl(),
            Instruction::BVC => self.bvc(),
            Instruction::BVS => self.bvs(),
            Instruction::CLC => self.flags.set(Flags::Carry, false),
            Instruction::CLD => self.flags.set(Flags::Decimal, false),
            Instruction::CLI => self.flags.set(Flags::IDisable, false),
            Instruction::CLV => self.flags.set(Flags::Overflow, false),
            Instruction::SEC => self.flags.set(Flags::Carry, true),
            Instruction::SED => self.flags.set(Flags::Decimal, true),
            Instruction::SEI => self.flags.set(Flags::IDisable, true),
            Instruction::BRK => self.brk(),
            Instruction::NOP => {}
            Instruction::RTI => self.rti(),
            Instruction::SRE => self.sre(),
            Instruction::LAX => self.lax(),
            Instruction::LAS => self.las(),
            Instruction::SHY => self.shy(),
            Instruction::RRA => self.rra(),
            Instruction::DCP => self.dcp(),
            Instruction::SAX => self.sax(),
            Instruction::RLA => self.rla(),
            Instruction::SLO => self.slo(),
            Instruction::ISC => self.isc(),
            Instruction::TAS => self.tas(),
            Instruction::LXA => self.lxa(),
            Instruction::JAM => self.jam(),
            Instruction::SHX => self.shx(),
            Instruction::SBX => self.sbx(),
            Instruction::ANE => self.ane(),
            Instruction::SHA => self.sha(),
            Instruction::ARR => self.arr(),
            Instruction::ALR => self.alr(),
            Instruction::ANC => self.anc(),
        };
    }
}
