# a 6502 code generator, generating instruction set
# generate file containing instructions with addressing modes
def create_header(file):
    header="""
// This file is auto-generated by InstructionGen.py
// DO NOT EDIT THIS FILE

#[derive(Debug, Clone, Copy)]
pub enum AddressingMode {
    Implicit,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
}

#[derive(Debug, Clone, Copy)]
pub enum Instructions {
    LDA,
    LDX,
    LDY,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TXA,
    TYA,
    TSX,
    TXS,
    PHA,
    PHP,
    PLA,
    PLP,
    AND,
    EOR,
    ORA,
    BIT,
    ADC,
    SBC,
    CMP,
    CPX,
    CPY,
    INC,
    INX,
    INY,
    DEC,
    DEX,
    DEY,
    ASL,
    LSR,
    ROL,
    ROR,
    JSR,
    RTS,
    JMP,
    JSR,
    RTS,
    BCC,
    BCS,
    BEQ,
    BMI,
    BNE,
    BPL,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    SEC,
    SED,
    SEI,
    BRK,
    NOP,
    RTI,
}

"""

match header = """
match instruction {
"""


match footer = """
}
"""
    file.write(header)

if __name__ == "__main__":
    file = open("instructions.rs", "w")
    create_header(file)
    file.close()
